version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 3
    versioning-strategy: lockfile-only
    groups:
      storybook:
        patterns:
          - 'storybook*'
          - '@storybook/*'
      angular:
        patterns:
          - '@angular*'
      fullcalendar:
        patterns:
          - '@fullcalendar*'          
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 3
    versioning-strategy: lockfile-only
